### ISSUE TITLE
How to generate an embedding for a given seuqence.

### ISSUE THREAD

**Issue by ozkilim** [basics-lab/qsft#1]
Thanks so much for you work! 

I may have missed the point slightly but are you able to generate an embedding from an amino acid sequence with this?

If so what script would you recommend I look at? 

I want to transform my sequences to "smooth" the epistatic landscape for downstream learning tasks.

Best,
Oz

**Comment by justinkang221** [comment]
Hi Oz,

I am not an expert in Biology at all, but let me try to answer your question. 

The point of this work is to compute a Fourier transform of a q-ary function. 

What does this mean for your landscape? Your landscape, along with basically any physical function you might think of lies in some "low-dimensional subspace" (loosely) within fourier space. What this can do is tell you what that subspace is if you provide a black-box model for your landscape. It will return some $k$-sparse length $q^n$ vector $F$ that succinctly represents your landscape. The more complicated your landscape, the larger k will be. (Keep in mind, the object is not literally some vector, but rather a list of non-zero coordinates since the true vector would be too large) 

The cool thing is, from this k-space vector, you can determine what a good embedding would be:

Let each sequence $s$ corresponds to some vector $g(s) = x \in \mathbb{C}^{q^{n}}$ (this mapping comes directly from the fourier transform). Then your landscape can be written as $L(s) \approx \langle F, g(s) \rangle$, but $F$ is mostly zeros. One thing you can do is to let $\sigma_F(y)$ be a vector that takes $y$ and removes all coordinates $i$ such that $F_i = 0$, so $\sigma_F(y) \in \mathbb{C}^{k}$. Then we have: 
$$L(s) \approx \langle \sigma_F(F), \sigma_F(g(s)) \rangle$$

Thus, I expect $\sigma_F(g(s))$, which maps onto the unit sphere to be a pretty good embedding. 
If you can get a good fourier transform, my expectation is that this would work well, but we would need to try it out!

If your problem is a full alphabet ($q=20+$) landscape, computing $F$ might be too hard, but one thing you can do is to consider some base sequence, and choose some subset of $m < n$ sites, then allow for mutations of only, say $5 < 20$ different types. This should make computing the fourier transform more tractable. You can then do this many times over, and get a bunch of embedding, and somehow combine them. That might be a good approach as well. 

Happy to discuss this further with you any time. You should be able to find my email in the paper linked in the README.

**Comment by erginbas** [comment]
Hello Oz,

To add to @justinkang221 's response, you can consider this workflow to construct your embeddings. First, you can obtain the dictionary of nonzero coefficients as the output of q-SFT. Then, for each non-zero coordinate vector $k_i \in \mathbb{Z}_q^n$ in that dictionary, you calculate $\phi_i := \omega^{\langle k_i, s \rangle}$ where $s$ is your sequence and $\omega = e^{j 2 \pi / q}$. Then, collecting the $\phi_i$ values into a vector would give you the embedding @justinkang221 described in his answer.

**Comment by ozkilim** [comment]
Dear @justinkang221 and @erginbas,

Thank you both so much for the in-depth responses!  I may write an email with a few further questions.

Best,
Oz
